version: "3.7"
services:
  app:
    build: ./docker
      args:
        user: igor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: library
    container_name: library-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - library

  db:
    image: mysql:5.7
    container_name: library-db
    restart: unless-stopped
    ports:
      - "33061:33061"
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - library

  nginx:
    image: nginx:alpine
    container_name: library-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - library

networks:
  library:
    driver: bridge